#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#add composer to path
export PATH="$HOME/.composer/vendor/bin:$PATH"
#add some more directories to PATH
export PATH=$PATH:"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/usr/local/git/bin:/usr/local/mysql/bin:/opt/local/bin"
# Source fresh shell

if [[ -s "${ZDOTDIR:-$HOME}/.fresh/build/shell.sh" ]]; then
  source ~/.fresh/build/shell.sh
fi

#search and replace
autoload -U zmv
